/**
 * Centralised sound effects.
 *
 * Components ask for a sound by name; they never construct audio, never hold a
 * volume, and never know where the files are. One module owns the audio context,
 * the buffer cache and the master gain, so adding a sound set later — or muting
 * everything — is a change in one place.
 *
 * Assets are ordinary local WAV files under public/sfx/, generated by
 * scripts/generate-sfx.mjs. Nothing is fetched from a third party at runtime.
 */

/**
 * A small family of tactile UI clicks, ordered roughly by weight.
 *
 * `tick` is the lightest and most frequent; `transition` is the heaviest and is
 * reserved for recomposing the map. `toggleOn` and `toggleOff` are one gesture in
 * two directions — the same contact made and released — so they are close relatives
 * rather than two different sounds, and a switch never sounds like a dropdown.
 *
 * There is deliberately nothing here for hover, drag or zoom. Continuous gestures
 * stay silent: a sound that fires whenever the pointer crosses a control is the one
 * thing in a set like this that reliably becomes irritating.
 */
export type SfxName =
  | 'tick'
  | 'click'
  | 'toggleOn'
  | 'toggleOff'
  | 'press'
  | 'confirm'
  | 'transition'

const SFX_FILES: Record<SfxName, string> = {
  tick: 'sfx/tick.wav',
  click: 'sfx/click.wav',
  toggleOn: 'sfx/toggleOn.wav',
  toggleOff: 'sfx/toggleOff.wav',
  press: 'sfx/press.wav',
  confirm: 'sfx/confirm.wav',
  transition: 'sfx/transition.wav',
}

/**
 * Ceiling applied on top of the user's setting.
 *
 * These are meant to sit under the work, not announce themselves, so "100%" in the
 * settings means "as loud as this app ever gets" rather than full scale.
 */
const MASTER_CEILING = 0.5

/**
 * Per-sound trim. The most frequent sound is the quietest, which is what keeps the
 * set from wearing thin over a long session.
 */
const SFX_GAIN: Record<SfxName, number> = {
  tick: 0.6,
  click: 0.7,
  toggleOn: 0.7,
  toggleOff: 0.62,
  press: 0.75,
  confirm: 0.8,
  transition: 0.85,
}

let context: AudioContext | null = null
let master: GainNode | null = null
let volume = 1
const buffers = new Map<SfxName, AudioBuffer>()
const pending = new Map<SfxName, Promise<AudioBuffer | null>>()

function ensureContext(): AudioContext | null {
  if (typeof window === 'undefined') return null
  if (!context) {
    const Ctor = window.AudioContext ?? (window as unknown as { webkitAudioContext?: typeof AudioContext }).webkitAudioContext
    if (!Ctor) return null
    context = new Ctor()
    master = context.createGain()
    master.gain.value = volume * MASTER_CEILING
    master.connect(context.destination)
  }
  return context
}

function load(name: SfxName): Promise<AudioBuffer | null> {
  const cached = pending.get(name)
  if (cached) return cached

  const request = (async () => {
    const ctx = ensureContext()
    if (!ctx) return null
    try {
      const response = await fetch(`${import.meta.env.BASE_URL}${SFX_FILES[name]}`)
      if (!response.ok) throw new Error(`sfx "${name}" ${response.status}`)
      const buffer = await ctx.decodeAudioData(await response.arrayBuffer())
      buffers.set(name, buffer)
      return buffer
    } catch (error) {
      console.warn('[sfx] could not load', name, error)
      return null
    }
  })()

  pending.set(name, request)
  return request
}

/** Sets the master volume, 0..1. Takes effect immediately, including mid-sound. */
export function setSfxVolume(next: number): void {
  volume = Math.max(0, Math.min(1, next))
  if (master && context) {
    // A short ramp instead of a jump, so dragging the slider does not click.
    master.gain.setTargetAtTime(volume * MASTER_CEILING, context.currentTime, 0.01)
  }
}

export function getSfxVolume(): number {
  return volume
}

/** Warms the cache so the first interaction is not silent while a file loads. */
export function preloadSfx(): void {
  for (const name of Object.keys(SFX_FILES) as SfxName[]) void load(name)
}

/**
 * Plays a sound. Silent at zero volume, and never throws — audio is a nicety and
 * must not be able to break an interaction.
 */
export function playSfx(name: SfxName): void {
  if (volume <= 0) return

  const ctx = ensureContext()
  if (!ctx || !master) return

  // Browsers start the context suspended until the user interacts with the page.
  if (ctx.state === 'suspended') void ctx.resume()

  const start = (buffer: AudioBuffer | null) => {
    if (!buffer || !context || !master || volume <= 0) return
    const source = context.createBufferSource()
    source.buffer = buffer
    const trim = context.createGain()
    trim.gain.value = SFX_GAIN[name]
    source.connect(trim)
    trim.connect(master)
    source.start()
  }

  const ready = buffers.get(name)
  if (ready) start(ready)
  else void load(name).then(start)
}
