/**
 * Centralised sound effects.
 *
 * Components ask for a sound by name; they never construct audio, never hold a
 * volume, and never know where the files are. One module owns the audio context,
 * the buffer cache and the master gain, so adding a sound set later — or muting
 * everything — is a change in one place.
 *
 * Assets are ordinary local WAV files under public/sfx/, generated by
 * scripts/generate-sfx.mjs. Nothing is fetched from a third party at runtime.
 */

/**
 * A small family of tactile UI clicks, ordered roughly by weight.
 *
 * `tick` is the lightest and most frequent; `transition` is the heaviest and is
 * reserved for recomposing the map. `toggleOn` and `toggleOff` are one gesture in
 * two directions — the same contact made and released — so they are close relatives
 * rather than two different sounds, and a switch never sounds like a dropdown.
 *
 * There is deliberately nothing here for hover, drag or zoom. Continuous gestures
 * stay silent: a sound that fires whenever the pointer crosses a control is the one
 * thing in a set like this that reliably becomes irritating.
 */
export type SfxName =
  | 'tick'
  | 'click'
  | 'toggleOn'
  | 'toggleOff'
  | 'press'
  | 'confirm'
  | 'transition'

const SFX_FILES: Record<SfxName, string> = {
  tick: 'sfx/tick.wav',
  click: 'sfx/click.wav',
  toggleOn: 'sfx/toggleOn.wav',
  toggleOff: 'sfx/toggleOff.wav',
  press: 'sfx/press.wav',
  confirm: 'sfx/confirm.wav',
  transition: 'sfx/transition.wav',
}

/**
 * Ceiling applied on top of the user's setting.
 *
 * These are meant to sit under the work, not announce themselves, so "100%" in the
 * settings means "as loud as this app ever gets" rather than full scale.
 */
const MASTER_CEILING = 0.5

/**
 * Per-sound trim. The most frequent sound is the quietest, which is what keeps the
 * set from wearing thin over a long session.
 */
const SFX_GAIN: Record<SfxName, number> = {
  tick: 0.6,
  click: 0.7,
  toggleOn: 0.7,
  toggleOff: 0.62,
  press: 0.75,
  confirm: 0.8,
  transition: 0.85,
}

let context: AudioContext | null = null
let master: GainNode | null = null
let volume = 1
const buffers = new Map<SfxName, AudioBuffer>()
const pending = new Map<SfxName, Promise<AudioBuffer | null>>()

/** Whether the context has actually been through a user gesture and started running. */
let unlocked = false
let unlockInstalled = false

function ensureContext(): AudioContext | null {
  if (typeof window === 'undefined') return null
  if (!context) {
    const Ctor = window.AudioContext ?? (window as unknown as { webkitAudioContext?: typeof AudioContext }).webkitAudioContext
    if (!Ctor) return null
    context = new Ctor()
    master = context.createGain()
    master.gain.value = volume * MASTER_CEILING
    master.connect(context.destination)
  }
  return context
}

function load(name: SfxName): Promise<AudioBuffer | null> {
  const cached = pending.get(name)
  if (cached) return cached

  const request = (async () => {
    const ctx = ensureContext()
    if (!ctx) return null
    try {
      const response = await fetch(`${import.meta.env.BASE_URL}${SFX_FILES[name]}`)
      if (!response.ok) throw new Error(`sfx "${name}" ${response.status}`)
      const buffer = await ctx.decodeAudioData(await response.arrayBuffer())
      buffers.set(name, buffer)
      return buffer
    } catch (error) {
      console.warn('[sfx] could not load', name, error)
      return null
    }
  })()

  pending.set(name, request)
  return request
}

/** Sets the master volume, 0..1. Takes effect immediately, including mid-sound. */
export function setSfxVolume(next: number): void {
  volume = Math.max(0, Math.min(1, next))
  if (master && context) {
    // A short ramp instead of a jump, so dragging the slider does not click.
    master.gain.setTargetAtTime(volume * MASTER_CEILING, context.currentTime, 0.01)
  }
}

export function getSfxVolume(): number {
  return volume
}

/**
 * Warms the cache so the first interaction is not silent while a file loads, and arms
 * the gesture listener that wakes the context on mobile.
 */
export function preloadSfx(): void {
  installUnlock()
  for (const name of Object.keys(SFX_FILES) as SfxName[]) void load(name)
}

/**
 * Wakes the context, from inside a real user gesture.
 *
 * Everything below exists because of one fact: `preloadSfx` runs when the app mounts,
 * so the context is constructed before anyone has touched anything, and a context
 * created outside a gesture starts *suspended*. On a desktop that resolves itself —
 * the first click resumes it and the sound plays. On a phone it does not, for three
 * separate reasons, and this handles all three.
 *
 * Playing a silent one-frame buffer is the second half of the wake-up. `resume()`
 * alone is not enough on iOS: the context reports `running` and stays mute until some
 * buffer has actually been started inside a gesture. One frame at the sample rate is
 * inaudible and costs nothing.
 */
function unlock(): void {
  const ctx = ensureContext()
  if (!ctx) return

  void ctx.resume()
  try {
    const source = ctx.createBufferSource()
    source.buffer = ctx.createBuffer(1, 1, ctx.sampleRate)
    source.connect(ctx.destination)
    source.start(0)
  } catch {
    // An unlock that fails is not worth breaking a tap over; the next gesture retries.
  }

  if (ctx.state === 'running') unlocked = true
}

/**
 * Listens for the first gesture, and for coming back from the background.
 *
 * The gesture list is deliberately broad and captured: whichever of `pointerdown`,
 * `touchend`, `mousedown` or `keydown` arrives first is the one that counts, and
 * capture means the map's own handlers cannot stop it from being seen. The listeners
 * remove themselves once the context is actually running.
 *
 * `visibilitychange` is the one that is easy to miss and the most annoying in practice.
 * iOS suspends the audio context when the page goes to the background — switch apps,
 * take a call, lock the phone — and it never resumes on its own. Without this, sound
 * works until the first interruption and is then silent for the rest of the session,
 * which reads as the feature being broken rather than as the browser having paused it.
 * `pageshow` covers the same thing for a page restored from the back/forward cache.
 */
function installUnlock(): void {
  if (unlockInstalled || typeof window === 'undefined') return
  unlockInstalled = true

  const events = ['pointerdown', 'touchend', 'mousedown', 'keydown'] as const
  const onGesture = () => {
    unlock()
    if (unlocked) {
      for (const type of events) window.removeEventListener(type, onGesture, true)
    }
  }
  for (const type of events) window.addEventListener(type, onGesture, true)

  const revive = () => {
    // `interrupted` is iOS's own state and is not in the DOM typings' union.
    if (context && (context.state as string) !== 'running') void context.resume()
  }
  document.addEventListener('visibilitychange', () => {
    if (document.visibilityState === 'visible') revive()
  })
  window.addEventListener('pageshow', revive)
}

/**
 * Plays a sound. Silent at zero volume, and never throws — audio is a nicety and
 * must not be able to break an interaction.
 */
export function playSfx(name: SfxName): void {
  if (volume <= 0) return

  const ctx = ensureContext()
  if (!ctx || !master) return

  const start = (buffer: AudioBuffer | null) => {
    if (!buffer || !context || !master || volume <= 0) return
    const source = context.createBufferSource()
    source.buffer = buffer
    const trim = context.createGain()
    trim.gain.value = SFX_GAIN[name]
    source.connect(trim)
    trim.connect(master)
    source.start()
  }

  const play = () => {
    const ready = buffers.get(name)
    if (ready) start(ready)
    else void load(name).then(start)
  }

  /*
   * Running is the normal case — every desktop interaction after the first, and every
   * mobile one after the unlock — and it takes exactly the path it always did.
   *
   * Suspended is the first tap on a phone, and the tap after coming back from the
   * background. Waiting for `resume()` to settle before starting is what makes that
   * first tap audible rather than swallowed: the old code resumed and started in the
   * same breath, and on a cold context the sound went nowhere.
   */
  if ((ctx.state as string) === 'running') play()
  else void ctx.resume().then(play, play)
}
