/**
 * The sticker gallery: ready-made faces, each a named combination of face-maker parts.
 *
 * A preset is only the parts — eyes, brows, mouth, extras — never a colour, so the whole gallery
 * is drawn in whichever colour the author picks, and every face can be opened in the face maker
 * to change. Original artwork throughout: these are expressions built from `faceMaker.ts`.
 */
import type { BrowId, ExtraId, EyeId, FaceOptions, MouthId } from './faceMaker'

export interface FacePreset {
  id: string
  name: string
  eyes: EyeId
  brows: BrowId
  mouth: MouthId
  extras: ExtraId[]
}

type Row = [name: string, eyes: EyeId, brows: BrowId, mouth: MouthId, extras?: ExtraId[]]

/*
 * The collection: a hundred faces after the reference sheets the author follows — each one's name and
 * idea, drawn in this face maker's own parts — then one for each of the author's hand gestures.
 */
const COLLECTION: Row[] = [
  ['Fire Punch', 'angry', 'angry', 'grit', ['firePunch', 'fist']],
  ['Shrug', 'wide', 'raised', 'frownSmall', ['shrug']],
  ['Heavy Breathing', 'wide', 'angry', 'fewTeeth', ['foreheadSweat', 'nose']],
  ['Checking You Out', 'smug', 'suspicious', 'smirk', ['point', 'fist']],
  ['Trying Not To Laugh', 'squeeze', 'none', 'lips', ['blush']],
  ['Hold Up', 'oneBig', 'angry', 'flat', ['shades', 'adjustShades']],
  ['Thumbs Down', 'angry', 'angry', 'pout', ['thumbsDown']],
  ['Rose in Teeth', 'smug', 'suspicious', 'troll', ['rose', 'floatHearts']],
  ['Sneaky Grin', 'halfSide', 'calm', 'fewTeeth'],
  ['Big Puppy Eyes', 'glossy', 'worried', 'wobble'],
  ['Fading Away', 'round', 'worried', 'frownSmall', ['byeLeft', 'motion', 'fadeAway']],
  ['Cat Face', 'cat', 'calm', 'kitty', ['catEars']],
  ['Thousand-Yard Stare', 'stare', 'weary', 'frownSmall', ['helmet']],
  ['Mewing', 'halfSide', 'worried', 'lips', ['mewing']],
  ['Troll Face', 'side', 'raised', 'troll'],
  ['Desperate', 'tearful', 'worried', 'tallShout', ['palmsUp', 'tears']],
  ['Ooh Face', 'halfSide', 'worried', 'ooh'],
  ['Shy', 'wide', 'worried', 'frownSmall', ['shyHands']],
  ['Party', 'oneBig', 'none', 'lips', ['partyBlower', 'partyHat', 'confetti', 'cheer']],
  ['Salute', 'angry', 'angry', 'blank', ['salute']],
  ['Not Impressed', 'tired', 'calm', 'pout'],
  ['Batter Up', 'tearful', 'angry', 'smirk', ['bat', 'foreheadSweat']],
  ['Double Thumbs Up', 'joy', 'raised', 'blank', ['doubleThumbs']],
  ['Suspicious Eye', 'oneBig', 'angry', 'frownSmall'],
  ['OK Sign', 'winkSide', 'worried', 'pout', ['okSign']],
  ['Thumbs Up', 'tired', 'calm', 'blank', ['thumbsUp']],
  ['Pointing And Laughing In Tears', 'squeeze', 'raised', 'openTeeth', ['pointLaugh', 'tears']],
  ['Thinking Face', 'round', 'suspicious', 'frownSmall', ['think']],
  ['In Shock', 'wide', 'raised', 'longO'],
  ['Happy and Cheering', 'joy', 'angry', 'openTeeth', ['cheer']],
  ['Innocent and Pretty', 'lashes', 'none', 'smile', ['blush']],
  ['Cookie Muncher', 'round', 'none', 'puff', ['cookie']],
  ['Snickering', 'halfSide', 'worried', 'puff', ['coverMouth']],
  ['Bawling', 'squeeze', 'worried', 'tallShout', ['waterfall', 'bawlFists']],
  ['Head Over Heels', 'hearts', 'raised', 'tongueOut', ['floatHearts']],
  ['Nervous Sweat', 'sad', 'worried', 'grimace', ['foreheadSweat']],
  ['Wearing Shades', 'round', 'none', 'lips', ['aviators', 'goatee']],
  ['Roaring Angry Beast', 'angry', 'angry', 'fangs'],
  ['Making an Argument', 'angry', 'angry', 'tallShout', ['palmsUp']],
  ['Shock', 'crazy', 'raised', 'longO'],
  ['Love from the Heart', 'joy', 'raised', 'blank', ['holdHeart']],
  ['Sad', 'sad', 'worried', 'pout'],
  ['Sexy Biting Lip', 'closed', 'none', 'bite'],
  ['Sad and Silently Crying', 'tearful', 'worried', 'pout', ['tears']],
  ['Confused', 'wide', 'raised', 'frownSmall', ['palmsUp']],
  ['Oops', 'wide', 'raised', 'flat', ['bothMouth']],
  ['Awkward Laugh', 'sad', 'worried', 'openTeeth'],
  ['Nerd', 'glossy', 'none', 'smile', ['nerdGlasses']],
  ['Smiling Face with Sunglasses', 'round', 'raised', 'troll', ['aviators']],
  ['Offering a Rose', 'closed', 'calm', 'blank', ['offerRose']],
  ['In Love', 'hearts', 'raised', 'drool'],
  ['Kiss', 'closed', 'calm', 'lips', ['floatHearts']],
  ['Impressed with Stars In Eyes', 'stars', 'none', 'openTeeth'],
  ['Blank Smile', 'wide', 'raised', 'blank'],
  ['Tearing Up', 'tearful', 'worried', 'pout'],
  ["Can't Look and Too Scared", 'round', 'worried', 'grimace', ['coverEyes']],
  ['Pleading Eyes', 'glossy', 'worried', 'pout'],
  ['Red Lips Kiss', 'closed', 'worried', 'redLips'],
  ['Evil Smirk', 'angry', 'angry', 'smirk'],
  ['Please', 'rolling', 'raised', 'flat', ['pray']],
  // The second sheet.
  ['Sleepy and Yawning', 'closed', 'floating', 'yawn', ['yawnHand']],
  ['Suspicious Heavy-Lidded', 'bags', 'calm', 'aside'],
  ['Unamused Face', 'tired', 'angry', 'wideFrown'],
  ['Very Touched', 'staring', 'floating', 'tiny', ['bigBlush', 'cheekHands']],
  ['Dumbfound', 'narrowed', 'angry', 'dotO'],
  ['Annoyed', 'fury', 'none', 'poutSide'],
  ['Appalled', 'staring', 'floating', 'tiny'],
  ['Devious', 'fury', 'none', 'smirk', ['rubFingers']],
  ['Flattered', 'lashes', 'none', 'smallSmile', ['bigBlush']],
  ['Derp', 'goofy', 'none', 'twoTeeth'],
  ['Smug Side-Eye', 'halfSide', 'suspicious', 'blank'],
  ['Worried', 'staring', 'floatingWorried', 'frownSmall'],
  ['Waving Hello', 'hopeful', 'raised', 'teeth', ['waveLeft']],
  ["Can't Unsee This", 'uneven', 'floatingOne', 'grimaceSide'],
  ['Wink', 'winkSide', 'none', 'smirk'],
  ['Goofy', 'goofy', 'floatingOne', 'bite'],
  ['Wacky Face', 'goofy', 'floating', 'wacky', ['pullMouth']],
  ['Seasick Smiley', 'goofy', 'floatingOne', 'pout', ['seasick']],
  ['Unimpressed', 'tired', 'none', 'tiny'],
  ['Displeased', 'tired', 'none', 'wideFlat'],
  ['Laughing It Off', 'squint', 'none', 'openTeeth', ['palmsUp']],
  ['Terrified', 'staring', 'floatingAngry', 'tallShout', ['strain']],
  ['Beaming', 'closed', 'none', 'teeth'],
  ['Knowing Smirk', 'hopeful', 'raised', 'smirk'],
  ['Huge Grin', 'hopeful', 'suspicious', 'teeth'],
  ['Instant Regret with Hands on Head', 'staring', 'none', 'grimaceSide', ['handsOnHead']],
  ['Face Palm', 'closed', 'none', 'flat', ['facepalm']],
  ['Mouth Open in Rage', 'fury', 'none', 'rageO'],
  ['Hush', 'hopeful', 'worried', 'lips', ['shush']],
  ['Hot Face', 'hot', 'floating', 'hangTongue', ['hotSweat']],
  ['Woozy Face', 'goofy', 'floatingOne', 'sideTongue'],
  ['Contented Grin', 'hopeful', 'floating', 'blank'],
  ['Drooling', 'staring', 'none', 'lipDrool'],
  ['Raspberry', 'narrowed', 'angry', 'blep'],
  ['Grumpy', 'fury', 'none', 'frownSmall'],
  ['Yikes', 'uneven', 'none', 'grimaceSide'],
  ['Give Me A Hug', 'closed', 'floating', 'blank', ['hug']],
  ['Punched in Face Black-Eye', 'blackEye', 'floatingWorried', 'sadOpen', ['plaster']],
  ['Tongue Out', 'hopeful', 'raised', 'tongueOut'],
  ['Growling Mad', 'fury', 'none', 'growl'],
  // The author's own hand gestures, each on a face of its own.
  ['Rock On', 'joy', 'angry', 'tongueOut', ['rockOn']],
  ['Clapping', 'joy', 'raised', 'openTeeth', ['clap']],
  ['Fist Bump', 'smug', 'calm', 'smile', ['fistBump']],
  ['Heart Hands', 'closed', 'raised', 'smile', ['heartHands', 'blush']],
  ['Taking Notes', 'halfSide', 'suspicious', 'flat', ['writing']],
  ['Call Me', 'wink', 'calm', 'smirk', ['callMe']],
  ['I Choose You', 'angry', 'angry', 'openTeeth', ['atYou']],
  ['Nope', 'tired', 'angry', 'flat', ['crossedArms']],
  ['Hold On', 'oneBig', 'raised', 'frownSmall', ['indexUp']],
  ['Gimme', 'crazy', 'angry', 'grit', ['claw']],
  ['Just A Tiny Bit', 'squeeze', 'worried', 'grimace', ['pinch']],
  ['Pretty Please', 'glossy', 'worried', 'wobble', ['clasped']],
  ['Love You', 'hearts', 'raised', 'smile', ['loveYou']],
  ['Stop Right There', 'angry', 'angry', 'flat', ['raisedHand']],
  ['Down There', 'side', 'raised', 'frownSmall', ['pointDown']],
  ['Finger Heart', 'wink', 'raised', 'smile', ['snap', 'floatHearts']],
]

/* More faces, made before the collection; any sharing a collection name gives way to it. */
const MORE: Row[] = [
  ['Grinning', 'round', 'calm', 'grin'],
  ['Big Laugh', 'happy', 'raised', 'laugh'],
  ['Tears of Joy', 'squint', 'raised', 'laugh', ['tears']],
  ['Trying Not To Laugh', 'closed', 'raised', 'puff', ['blush']],
  ['Smug', 'smug', 'suspicious', 'smirk'],
  ['Checking You Out', 'smug', 'suspicious', 'smirk', ['point']],
  ['Side Eye', 'side', 'calm', 'flat'],
  ['Suspicious', 'side', 'angry', 'flat'],
  ['Eye Roll', 'rolling', 'none', 'flat'],
  ['Unimpressed', 'tired', 'none', 'flat'],
  ['Bored', 'tired', 'worried', 'flat'],
  ['Sleepy', 'closed', 'none', 'flat', ['zzz']],
  ['Exhausted', 'tired', 'worried', 'wobbly', ['sweat']],
  ['Angry', 'angry', 'angry', 'frown'],
  ['Furious', 'angry', 'angry', 'grit', ['anger']],
  ['Rage', 'squint', 'angry', 'shout', ['anger', 'steam']],
  ['Fire Punch', 'angry', 'angry', 'grit', ['firePunch']],
  ['Fuming', 'angry', 'angry', 'grimace', ['steam']],
  ['Grumpy', 'angry', 'thick', 'frown'],
  ['Annoyed', 'side', 'angry', 'flat', ['anger']],
  ['Sad', 'sad', 'worried', 'frown'],
  ['Crying', 'sad', 'worried', 'frown', ['tears']],
  ['Sobbing', 'squint', 'worried', 'shout', ['tears']],
  ['Puppy Eyes', 'puppy', 'worried', 'wobbly'],
  ['Pleading', 'puppy', 'worried', 'oh'],
  ['Disappointed', 'tired', 'worried', 'frown'],
  ['Thumbs Down', 'tired', 'angry', 'frown', ['thumbsDown']],
  ['Thumbs Up', 'joy', 'calm', 'smile', ['thumbsUp']],
  ['Approved', 'wink', 'calm', 'grin', ['thumbsUp']],
  ['Waving', 'happy', 'raised', 'grin', ['wave']],
  ['Hello', 'round', 'raised', 'smile', ['wave']],
  ['Peace', 'wink', 'calm', 'tongue', ['peace']],
  ['Shrug', 'side', 'raised', 'flat', ['shrug']],
  ['Whatever', 'rolling', 'raised', 'smirk', ['shrug']],
  ['Facepalm', 'closed', 'worried', 'frown', ['facepalm']],
  ['Salute', 'round', 'calm', 'smile', ['salute']],
  ['Thinking', 'side', 'suspicious', 'flat', ['think']],
  ['Hmm', 'rolling', 'suspicious', 'wobbly', ['think']],
  ['Idea', 'wide', 'raised', 'grin', ['bulb']],
  ['Confused', 'side', 'worried', 'wobbly', ['question']],
  ['Shocked', 'wide', 'raised', 'oh'],
  ['Surprised', 'wide', 'raised', 'wow'],
  ['Scared', 'wide', 'worried', 'grimace', ['sweat']],
  ['Terrified', 'wide', 'worried', 'shout', ['sweat']],
  ['Panic', 'crazy', 'worried', 'shout', ['sweat', 'exclaim']],
  ['Nervous', 'round', 'worried', 'wobbly', ['sweat']],
  ['Awkward', 'side', 'worried', 'grimace', ['sweat']],
  ['Heavy Breathing', 'wide', 'raised', 'puff', ['sweat', 'nose']],
  ['Embarrassed', 'closed', 'worried', 'smile', ['blush', 'sweat']],
  ['Shy', 'joy', 'worried', 'smile', ['blush']],
  ['In Love', 'hearts', 'calm', 'grin', ['blush']],
  ['Love Struck', 'hearts', 'raised', 'laugh', ['floatHearts']],
  ['Kiss', 'closed', 'calm', 'kiss', ['blush', 'floatHearts']],
  ['Blowing a Kiss', 'wink', 'calm', 'kiss', ['floatHearts']],
  ['Rose in Teeth', 'smug', 'suspicious', 'teeth', ['rose']],
  ['Flirty', 'wink', 'suspicious', 'smirk', ['blush']],
  ['Cool', 'round', 'calm', 'smirk', ['shades']],
  ['Hold Up', 'side', 'suspicious', 'flat', ['shades', 'point']],
  ['Boss', 'round', 'calm', 'smile', ['shades', 'crown']],
  ['King', 'smug', 'raised', 'smirk', ['crown']],
  ['Party', 'happy', 'raised', 'laugh', ['partyHat', 'sparkles']],
  ['Celebrate', 'joy', 'raised', 'grin', ['partyHat']],
  ['Star Struck', 'stars', 'raised', 'laugh', ['sparkles']],
  ['Amazed', 'stars', 'raised', 'oh'],
  ['Rich', 'money', 'raised', 'sly'],
  ['Money Eyes', 'money', 'raised', 'grin', ['sparkles']],
  ['Greedy', 'money', 'angry', 'sly'],
  ['Dizzy', 'dizzy', 'worried', 'oh'],
  ['Hypnotized', 'spiral', 'none', 'flat'],
  ['Crazy', 'crazy', 'raised', 'tongue'],
  ['Goofy', 'crazy', 'suspicious', 'laugh'],
  ['Silly', 'wink', 'raised', 'tongue'],
  ['Tongue Out', 'happy', 'calm', 'tongue'],
  ['Cheeky', 'wink', 'suspicious', 'tongue', ['blush']],
  ['Yummy', 'joy', 'raised', 'tongue', ['blush']],
  ['Drooling', 'wide', 'raised', 'drool'],
  ['Zipped', 'round', 'calm', 'zip'],
  ['Secret', 'side', 'suspicious', 'zip'],
  ['Speechless', 'wide', 'none', 'flat'],
  ['Grimace', 'round', 'worried', 'grimace'],
  ['Cringe', 'squint', 'worried', 'grimace'],
  ['Lip Bite', 'smug', 'calm', 'bite'],
  ['Mischief', 'smug', 'angry', 'sly'],
  ['Evil Grin', 'angry', 'angry', 'sly'],
  ['Sly', 'side', 'suspicious', 'sly'],
  ['Feeling Sick', 'tired', 'worried', 'oh', ['sweat']],
  ['Hurt', 'squint', 'worried', 'grimace', ['bandage']],
  ['Angel', 'joy', 'calm', 'smile', ['halo']],
  ['Innocent', 'round', 'raised', 'smile', ['halo', 'blush']],
  ['Nerd', 'round', 'raised', 'teeth', ['glasses']],
  ['Smart', 'smug', 'calm', 'smirk', ['glasses']],
  ['Fancy', 'round', 'raised', 'smile', ['monocle', 'mustache']],
  ['Gentleman', 'smug', 'calm', 'smirk', ['mustache']],
  ['Music', 'closed', 'calm', 'smile', ['headphones', 'notes']],
  ['DJ', 'happy', 'raised', 'laugh', ['headphones']],
  ['Whistling', 'side', 'calm', 'whistle', ['notes']],
  ['Innocent Whistle', 'rolling', 'raised', 'whistle'],
  ['Shout', 'angry', 'angry', 'shout'],
  ['Yelling', 'squint', 'angry', 'shout', ['exclaim']],
  ['Wow', 'wide', 'raised', 'wow', ['exclaim']],
  ['What?', 'crazy', 'raised', 'wow', ['question']],
  ['Pouting', 'side', 'angry', 'kiss'],
  ['Determined', 'angry', 'angry', 'flat', ['fist']],
  ['Strong', 'joy', 'angry', 'grin', ['fist']],
  ['Winner', 'happy', 'raised', 'grin', ['crown', 'sparkles']],
  ['Hero', 'smug', 'raised', 'smile', ['sparkles']],
  ['Chill', 'tired', 'calm', 'smile', ['shades']],
  ['Out of It', 'spiral', 'worried', 'tongue'],
]

const taken = new Set(COLLECTION.map(([name]) => name.toLowerCase()))
const ROWS: Row[] = [...COLLECTION, ...MORE.filter(([name]) => !taken.has(name.toLowerCase()))]

const slug = (name: string) =>
  name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')

/** How many of `FACE_PRESETS` are the collection, which comes first. */
export const COLLECTION_SIZE = COLLECTION.length

export const FACE_PRESETS: FacePreset[] = ROWS.map(([name, eyes, brows, mouth, extras = []]) => ({
  id: slug(name),
  name,
  eyes,
  brows,
  mouth,
  extras,
}))

/** A preset as face-maker options, in `color`. */
export function presetFace(preset: FacePreset, color: string): FaceOptions {
  return { color, eyes: preset.eyes, brows: preset.brows, mouth: preset.mouth, extras: [...preset.extras], outline: false }
}
