/**
 * Which flags exist on disk, by ISO 3166-1 alpha-2.
 *
 * Generated by `scripts/prepare-flags.mjs` — do not edit by hand.
 *
 * The renderer checks this before requesting a file, so an entity without artwork
 * falls back to ordinary land instead of asking for a URL that is not there.
 */
export const FLAG_CODES: ReadonlySet<string> = new Set(["ad","ae","af","ag","ai","al","am","ao","aq","ar","as","at","au","aw","ax","az","ba","bb","bd","be","bf","bg","bh","bi","bj","bl","bm","bn","bo","bq","br","bs","bt","bv","bw","by","bz","ca","cc","cd","cf","cg","ch","ci","ck","cl","cm","cn","co","cr","cu","cv","cw","cx","cy","cz","de","dj","dk","dm","do","dz","ec","ee","eg","eh","er","es","et","fi","fj","fk","fm","fo","fr","ga","gb","gd","ge","gf","gg","gh","gi","gl","gm","gn","gp","gq","gr","gs","gt","gu","gw","gy","hk","hm","hn","hr","ht","hu","id","ie","il","im","in","io","iq","ir","is","it","je","jm","jo","jp","ke","kg","kh","ki","km","kn","kp","kr","kw","ky","kz","la","lb","lc","li","lk","lr","ls","lt","lu","lv","ly","ma","mc","md","me","mf","mg","mh","mk","ml","mm","mn","mo","mp","mq","mr","ms","mt","mu","mv","mw","mx","my","mz","na","nc","ne","nf","ng","ni","nl","no","np","nr","nu","nz","om","pa","pe","pf","pg","ph","pk","pl","pm","pn","pr","ps","pt","pw","py","qa","re","ro","rs","ru","rw","sa","sb","sc","sd","se","sg","sh","si","sj","sk","sl","sm","sn","so","sr","ss","st","sv","sx","sy","sz","tc","td","tf","tg","th","tj","tk","tl","tm","tn","to","tr","tt","tv","tw","tz","ua","ug","um","us","uy","uz","va","vc","ve","vg","vi","vn","vu","wf","ws","xk","xn","xs","ye","yt","za","zm","zw","x-rome","x-yug","x-ussr","x-qing","x-brit","x-scot","x-wales","x-nire","x-mold","x-tran","x-austria","x-rusemp","x-ah"])

/**
 * Entities whose flag is not the one their own code would find.
 *
 * Every entry comes from `scripts/territory-flags.mjs`, where the reason for it is
 * written down. Consulted before an entity's own iso2, so a territory that flies
 * another state's flag resolves to that state's artwork.
 */
export const FLAG_ALIASES: ReadonlyMap<string, string> = new Map([["XSO","xs"],["XNC","xn"],["XAK","gb"],["XDH","gb"],["XGB","us"],["XCP","fr"],["XIO","au"],["XCS","au"]])

/**
 * Flags that belong to no country in the dataset, offered by name.
 *
 * Historical and regional artwork a merged entity can fly. Every one is the Wikimedia
 * Commons file named in `scripts/historical-flags.mjs`, stored verbatim — the name
 * here is what the flag chooser searches on.
 */
export const FLAG_EXTRAS: ReadonlyArray<{ code: string; name: string }> = [{"code":"x-rome","name":"Roman Empire"},{"code":"x-yug","name":"Yugoslavia"},{"code":"x-ussr","name":"Soviet Union"},{"code":"x-qing","name":"Qing Dynasty"},{"code":"x-brit","name":"British Empire"},{"code":"x-scot","name":"Scotland"},{"code":"x-wales","name":"Wales"},{"code":"x-nire","name":"Northern Ireland"},{"code":"x-mold","name":"Moldavia"},{"code":"x-tran","name":"Transylvania"},{"code":"x-austria","name":"Austrian Empire"},{"code":"x-rusemp","name":"Russian Empire"},{"code":"x-ah","name":"Austria-Hungary"}]
